[[CURRENCIES]]
code="MNY"
issuer="GDUUE4MDLA2LNJ7Z22M5LTHY6H5BBUIYHX4FLZBAPAE6SQ6R3G2K66I3"
display_decimals=2 
name="mannycoin"
desc="1 manny coin entitles you to 1 share of manny's shit brain."
conditions="you must hodl and cherish your mannycoin forever."
image="https://i.imgur.com/qsIwlCc.png"
